.TH frost 8 "21st April 2012"
.SH NAME
.B frost
\- Suspend the system
.SH SYNOPSIS
.B frost
[OPTION]...
.SH DESCRIPTION
Suspend the system, either to RAM or a swap partition, if there is any.
SH OPTIONS
.TP 5
.B -h
Show a help message and quit
.TP
.B -m
Suspend to RAM
.TP
.B -s
Suspend to disk
.TP 0

Only one mode may be specified at a time.
.SH SEE ALSO
halt(8)
.SH BUGS
.B frost
has no known bugs.
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)