.TH frost 8 "21st April 2012"
.SH NAME
.B frost
\- suspend the system
.SH SYNOPSIS
.B frost
[OPTION]...
.SH DESCRIPTION
Suspend the system, either to RAM or a swap partition, if there is any.

Only one mode may be specified at a time.

.TP
.B -h
Show a help message and quit
.TP
.B -m
Suspend to RAM
.TP
.B -s
Suspend to disk
.SH BUGS
.B frost
has no known bugs.
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
